services:
  - type: web
    name: post-meeting-social-generator
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: post-meeting-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://post-meeting-social-generator.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RECALL_API_KEY
        sync: false

databases:
  - name: post-meeting-db
    plan: free
