services:
  - type: web
    name: post-meeting-social-generator
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEMO_MODE
        value: "true"
      - key: NEXTAUTH_URL
        value: https://post-meeting-social-media-generator-4.onrender.com
      - key: NEXTAUTH_SECRET
        value: "demo-secret-key-for-presentation-only-32-chars"
      - key: DATABASE_URL
        value: "postgresql://demo:demo@demo:5432/demo"
      - key: OPENAI_API_KEY
        value: "demo-openai-key"
      - key: GOOGLE_CLIENT_ID
        value: "demo-google-client-id"
      - key: GOOGLE_CLIENT_SECRET
        value: "demo-google-client-secret"
      - key: RECALL_API_KEY
        value: "demo-recall-api-key"

databases:
  - name: post-meeting-db
    plan: free
